services:
  # Django API service
  - type: web
    name: nyure-education-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn -c gunicorn_config.py nyure_education.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,ed.nyure.com.np
      - key: DATABASE_URL
        fromDatabase:
          name: nyure-education-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://ed.nyure.com.np

  # Frontend service (optional if you're deploying frontend elsewhere)
  - type: web
    name: course-compass-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://nyure-education-api.onrender.com/api

# Database
databases:
  - name: nyure-education-db
    databaseName: nyure_education
    user: nyure_user
    plan: starter
